/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_m4399_recharge_control_strategy_sign_SignUtils */

#ifndef _Included_cn_m4399_recharge_control_strategy_sign_SignUtils
#define _Included_cn_m4399_recharge_control_strategy_sign_SignUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_m4399_recharge_control_strategy_sign_SignUtils
 * Method:    nativeEncode
 * Signature: ([Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_m4399_recharge_control_strategy_sign_SignUtils_nativeEncode
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     cn_m4399_recharge_control_strategy_sign_SignUtils
 * Method:    nativeDecode
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_m4399_recharge_control_strategy_sign_SignUtils_nativeDecode
  (JNIEnv *, jclass, jstring);

/*
 * Class:     cn_m4399_recharge_control_strategy_sign_SignUtils
 * Method:    nativeGetMark
 * Signature: ([Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_m4399_recharge_control_strategy_sign_SignUtils_nativeGetMark
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     cn_m4399_recharge_control_strategy_sign_SignUtils
 * Method:    nativeValidate
 * Signature: ([Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_m4399_recharge_control_strategy_sign_SignUtils_nativeValidate
  (JNIEnv *, jclass, jobjectArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
